# Generated by Django 4.0.3 on 2022-03-18 12:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='azertyuiopqsdfghjkl', editable=False, populate_from='titre'),
            preserve_default=False,
        ),
    ]
